# Generated by Django 2.1 on 2018-08-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_courseorg_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='tag',
        ),
    ]
