# Generated by Django 2.1 on 2018-08-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180816_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='aadd_time',
            new_name='add_time',
        ),
    ]
